name: BotDetection
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - tweepy
  - gensim
  - pandas
  - pytorch=1.0.1
  - torchvision==0.2.1
  - numpy
  - tqdm
  - matplotlib
  - scikit-learn
#  # all pip dependencies
  - pip
  - pip:
    - astar-tcn --no-dependencies
    - nltk
    - pywikibot
    - langdetect
    - pillow